language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt

script:
  - cd /home/travis/build/makism/dyfunconn/tests/
  - nosetests --cover-tests --with-coverage --cover-package=dyfunconn

after_success:  
  - coveralls
